#!/bin/bash

usage () {
  echo "Usage: $0 ATTRIBUTE_NAME FILE" >&2
  echo "Supported Attributes:"
  echo "		      bashProfile"
  echo "		      bashProfile2"
  echo "		      bashProfile3"
  echo "		      screenrc"
  echo "		      vimrc"
  echo "		      tmuxrc"
  echo "		      bashLogout"
  exit 1
}

ldapmod () {
USERNAME=$USER
ATTRIBUTE=$1
BINDUSER="uid=$USERNAME,ou=People,dc=example,dc=org"
LDAPHOST=ldap.example.org
echo -n "Enter your LDAP Password: "
read -s BINDPW
echo

echo \
"dn: uid=$USERNAME,ou=People,dc=example,dc=org
changetype: modify
replace: $ATTRIBUTE
$ATTRIBUTE:: $INPUTFILE" \
\
| ldapmodify -c -x -ZZ -h $LDAPHOST -D "$BINDUSER" -w "$BINDPW" &>/dev/null && echo "Success! The $ATTRIBUTE was added to the $USERNAME account." || echo "FAIL! The $ATTRIBUTE was not added to the $USERNAME account." 
}

INPUTFILE="$(gzip -c $2 | openssl enc -base64 | tr -d '\n')"

if [ "$#" -ne 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage
fi

if [ "$1" != "bashProfile" ] && [ "$1" != "bashProfile2" ] && [ "$1" != "bashProfile3" ] && [ "$1" != "screenrc" ] && [ "$1" != "vimrc" ] && [ "$1" != "tmuxrc" ] && [ "$1" != "bashLogout" ]; then
  echo "=============================="
  echo "Incorrect attribute specified."
  echo "=============================="
  echo
  usage
fi

if [ ! -f "$2" ] || [ ! -s "$2" ]; then
  echo "========================"
  echo "Could not read your file"
  echo "========================"
  echo
  usage
fi

if [ "$(echo $INPUTFILE | wc -c)" -gt 4076 ]; then
  echo "=============================================================="
  echo "Inputfile is too large. Must compress to less than 4076 bytes."
  echo "=============================================================="
  exit 2
fi

ldapmod $1 $2
