#!/bin/bash

if [ "$#" -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage: $0 USERNAME " >&2
  exit 1
fi


USERNAME=$1
BINDUSER="cn=Directory Manager"
BINDPW=dir_man_password
LDAPHOST=ldap.example.com

echo \
"dn: uid=$USERNAME,ou=People,dc=example,dc=com
changetype: modify
add: objectclass
objectclass: ldapProfile" \
\
| ldapmodify -vc -x -ZZ -h $LDAPHOST -D "$BINDUSER" -w "$BINDPW" 
